### ISSUE TITLE
usage방식 변경 요청

### ISSUE THREAD

**Issue by whatugonnado** [geeksbaek/goinside-image-crawler#2]
-gall 이후 갤 url을 다 적는데, 그냥 맨 뒤 programming 만 적게끔 하면 어떰? 마이너갤은 -mgall 이렇게 패러미터 넘겨주고 하면 쓰기  편할텐데

**Comment by geeksbaek** [comment]
모바일웹 파싱하는거라 아마 마이너갤 일반갤 구분안해도 구조가 같아서 처리될거임. 

flag를 url이랑 gall로 구분하는 건 어떰? -url 로는 url을 전달할 수 있고 -gall 은 갤러리 id를 전달할 수 있게, 둘 중 하나만 전달되도 되도록, 본인같은 경우는 그냥 주소창에서 url 싹 복사해서 붙여넣는게 편해서 url 방식은 남겨두고 싶음.

**Comment by whatugonnado** [comment]
url은 피씨버전, 모바일버전 다 지원하는거고?

**Comment by geeksbaek** [comment]
ㅇㅇ url 들어오면 정규식으로 id값 뽑아내서 모바일 방식 url로 포맷팅함. 정상적인 url 아니라도 id 뽑는 정규식에 매칭만 되면 인식됨

**Comment by whatugonnado** [comment]
굳굳

**Comment by geeksbaek** [comment]
적용된 바이너리임 https://github.com/geeksbaek/goinside-image-crawler/releases/tag/1.0.6 

설명은 readme 참조 https://github.com/geeksbaek/goinside-image-crawler/commit/ca01ef73dc8477ce9d68d6053ceec52efb9307be
